Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Autenticação Torcedor API Test
+name: Regressivo - API
 
 on: 
   workflow_dispatch:
@@ -24,10 +24,24 @@ jobs:
           sleep 5
 
       - name: Executar os testes
-        run: npm test
+        run: npx mocha ./test/pipelines.test --reporter mochawesome --reporter-options reportDir=mochawesome-report,reportFilename=index,reportJson=true
+        continue-on-error: true
 
-      - name: Salvar relatório Mochawesome
+      - name: Verificar conteúdo do relatório
+        run: ls -R mochawesome-report || echo "Relatório não encontrado"
+      
+      - name: Upload do relatório Mochawesome
         uses: actions/upload-artifact@v4
         with:
           name: mochawesome-report
           path: mochawesome-report/
+          
+      - name: Validar sucesso dos testes
+        run: |
+          FAILURES=$(jq '.stats.failures' mochawesome-report/mochawesome.json)
+          if [ "$FAILURES" -gt 0 ]; then
+            echo "❌ Testes falharam: $FAILURES falhas encontradas"
+            exit 1
+          else
+            echo "✅ Todos os testes passaram"
+          fi
